login/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.account.urls")),
    path('', include("apps.taplink.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/account/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, BaseUserManager
from phonenumber_field.modelfields import PhoneNumberField
from django.urls import reverse
from django.db import models
from django.utils import timezone


class UserManager(BaseUserManager):

    """Class which specifies superuser"""

    def create_user(self, phone_number, password, **kwargs):
        if not phone_number:
            raise ValueError('Номер телефона должен быть')
        user = self.model(phone_number=phone_number, **kwargs)
        if password:
            user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, **kwargs):
        user = self.create_user(**kwargs)
        user.set_password(kwargs['password'])
        user.is_superuser = True
        user.is_active = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(PermissionsMixin, AbstractBaseUser):

    """User class with 'phone_number' field instead of username"""

    phone_number = PhoneNumberField(unique=True, max_length=15, verbose_name='Номер телефона')
    first_name = models.CharField(max_length=150, verbose_name="Имя")
    last_name = models.CharField(max_length=150, verbose_name="Фамилия")
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    joined_data = models.DateTimeField(verbose_name="Дата добавления", default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = 'phone_number'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def get_absolute_url(self):
        return reverse('get_profile', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.phone_number)

apps/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.contrib.auth import get_user_model

User = get_user_model()


class RegistrationForm(UserCreationForm):
    """ Form for creating new user"""

    phone_number = forms.CharField(widget=forms.TextInput(attrs={'id': 'phone_number', 'hidden': True}))

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
        ]


class ChangePasswordForm(PasswordChangeForm):
    """Overwritten form for changing users password"""

    def __init__(self, *args, **kwargs):
        super(ChangePasswordForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget = forms.PasswordInput(attrs={'class': 'form_input',
                                                                        'placeholder': 'Введите старый пароль'})
        self.fields['new_password1'].widget = forms.PasswordInput(attrs={'class': 'form_input',
                                                                         'placeholder': 'Введите новый пароль'})
        self.fields['new_password2'].widget = forms.PasswordInput(attrs={'class': 'form_input',
                                                                         'placeholder': 'Повторите новый пароль'})


class PasswordResetForm(forms.Form):
    """Form used for reset password"""

    firebase_token = forms.CharField(widget=forms.TextInput(attrs={"id": 'firebase_token'}))

    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
    )
    new_password2 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
    )
    error_messages = {
        'password_mismatch': 'Пароли не совпадают.',
        'password_short': 'Пароль слишком короткий.',
        'space_in_password': 'Пароль не должен содердать пробелы'
    }

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        if ' ' in password1:
            raise ValidationError(
                self.error_messages['space_in_password'],
                code='space_in_password'
            )
        if len(password2) < 7:
            raise ValidationError(
                self.error_messages['password_short'],
                code='password_short'
            )
        return password2


class PhoneNumberForm(forms.Form):
    """Form used for changing users number"""

    phone_number = forms.CharField(widget=forms.TextInput(attrs={'id': 'phone_number'}))

templates/pages/change-number-submit.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}

{% block content %}

    <div class="box__wrap">
        <div class="form__box">
            <form action="">
                <div class="form__box-head">
                    <h2 class="form__title">
                        Подтверждение номера
                        телефона
                    </h2>
                </div>
                <div class="check__number">
                    <div class="profile__icon">
                        <svg width="40" height="41" viewBox="0 0 40 41" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M36.0994 36.4314C35.1498 33.7735 33.0574 31.4248 30.1467 29.7497C27.2359 28.0746 23.6696 27.1666 20.0007 27.1666C16.3318 27.1666 12.7654 28.0746 9.85463 29.7497C6.94389 31.4248 4.85147 33.7735 3.90189 36.4314"
                                  stroke="#979797" stroke-width="3" stroke-linecap="round"/>
                            <ellipse cx="19.9993" cy="13.8333" rx="8.33333" ry="8.33333" stroke="#979797"
                                     stroke-width="3" stroke-linecap="round"/>
                        </svg>
                    </div>
                    <div>
                        <p class="check__number-number">
                            +996 700 12 34 56
                        </p>
                        <a href="#" class="wrong__number">
                            Неверный номер телефона?
                        </a>
                    </div>
                </div>
                <label class="form__input-wrap">
                    <input type="text" class="form__input" placeholder="Введите код подтверждения" required>
                </label>
                <button class="form__btn" type="submit">
                    Подтвердить
                </button>
                <a href="" class="no__sms">
                    Не пришло SMS сообщение?
                </a>
                <button class="sms__timer" type="submit" disabled>
                    Отправить снова через 0:<span class="timer__seconds">59</span>
                </button>
            </form>
        </div>
    </div>

{% endblock %}

{% block scripts %}{% endblock %}

templates/pages/change-number.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}

{% block content %}
    <div id="myDIV">
        <div class="box__wrap">
            <div class="form__box">
                <form  id="id_number" action="{% url 'check-number' %}">
                    {% csrf_token %}
                    <div class="form__box-head">
                        <h2 class="form__title">
                            Введите новый номер
                        </h2>
                    </div>
                    <label class="form__input-wrap">
                        <input type="text" id="phone_number" name="phone_number" class="form__input form__input-tel" required>
                    </label>
                    <div style="text-align: center">{{ form.errors }}</div>

                    <button id="sign-in-button" class="form__btn"  onclick="passwordForm">
                        Сохранить изменения
                    </button>
                </form>
            </div>
        </div>
        <div class="success__notification">
        Номер успешно изменен
    </div>
</div>
        <button id='sign-in-button' hidden></button>

{% endblock %}
{% block scripts %}
<script src="{% static 'js/phone_number_change.js' %}"></script>
{% endblock %}

templates/pages/change-password.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}

{% block content %}

    <div class="box__wrap">
        <div class="form__box">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form__box-head">
                    <h2 class="form__title">
                        Придумайте новый пароль
                    </h2>
                </div>
                <label class="form__input-wrap form__password-input-wrap">
                    <input type="password" id="id_old_password" name="old_password" class="form__input" placeholder="Введите старый пароль" required>
                    <div class="form__eye"></div>
                </label>
                <label class="form__input-wrap form__password-input-wrap">
                    <input type="password" id="id_new_password1" name="new_password1" class="form__input" placeholder="Придумайте новый пароль" required>
                    <div class="form__eye"></div>
                </label>
                <label class="form__input-wrap form__password-input-wrap">
                    <input type="password" id="id_new_password2" name="new_password2" class="form__input" placeholder="Повторите пароль" required>
                    <div class="form__eye"></div>
                </label>
                {{ form.error }}
                <button class="form__btn" type="submit">
                    Сохранить изменения
                </button>
            </form>
        </div>
    </div>
    <div class="success__notification">
        Пароль успешно изменен
    </div>
{% endblock %}

{% block scripts %}{% endblock %}

templates/pages/edit-profile.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}

{% block content %}

    <div class="box__wrap">
        <div class="form__box">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form__box-head">
                    <h2 class="form__title">
                        Профиль
                    </h2>
                    <a href="{% url 'logout' %}" class="form__reg form__sign-out">
                        Выход
                    </a>
                </div>
                <label class="form__input-wrap">
                    <h4>{{ user.phone_number }}<hr><br>{{ user.first_name }}</h4>
                    <input type="text" class="form__input" id="id_first_name" name="first_name" placeholder="Введите новое имя" required>
                </label>
                <label class="form__input-wrap">
                <h4>{{ user.last_name }}</h4>
                    <input type="text" class="form__input" id="id_last_name" name="last_name" placeholder="Введите новую фамилию" required>
                </label>
                <button class="form__btn" type="submit">
                    Сохранить изменения
                </button>
                <a href="{% url 'old-password-change' %}" class="sms__timer change__filed">
                    Сменить пароль
                </a>
                <a href="{% url 'change-number' %}" class="sms__timer change__filed">
                    Сменить номер
                </a>
            </form>
        </div>
    </div>

{% endblock %}

{% block scripts %}{% endblock%}

templates/pages/password-reset-number.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}

{% block content %}
    <div id="changeble_div">
        <div class="box__wrap" id="number_validate_id">
            <div class="form__box">
                <form  action="{% url 'is-user-exists' %}" id="phone-password" >
                    {% csrf_token %}
                    <div class="form__box-head">
                        <h2 class="form__title">
                            Для восстановления пароля, введите номер телефона
                        </h2>
                    </div>
                    <label class="form__input-wrap">
                        <input id="phone_number_password_id" type="text" class="form__input form__input-tel" required>
                    </label>
                    <button class="form__btn" type="submit">
                        Отправить код
                    </button>
                </form>
            </div>
        </div>
    </div>
    <button id='sign-in-button' hidden></button>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/number_password_reset.js' %}"></script>

{% endblock %}

templates/pages/password-reset.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}

{% block content %}

    <div class="box__wrap" id="number_validate_id">
        <div class="form__box">
            <form id="password-reset-form" action="" method="post" >
                {% csrf_token %}
                <div class="form__box-head">
                    <h2 class="form__title">
                        Новый пароль
                    </h2>
                </div>
                <label class="form__password-input-wrap">
                    <input id="firebase_token" name="firebase_token" type="hidden" class="form__input"  required>
                </label>

                <label class="form__input-wrap form__password-input-wrap">
                    <input id="id_new_password1" name="new_password1" type="password" class="form__input" placeholder="Введите новый пароль" autocomplete="new-password" required>
                    <div class="form__eye"></div>
                </label>
                <label class="form__input-wrap form__password-input-wrap">
                    <input id="id_new_password2"  name="new_password2" type="password" class="form__input" placeholder="Повторите пароль" autocomplete="new-password" required>
                    <div class="form__eye"></div>
                </label>
                <div style="text-align: center">{{ form.errors }}</div>
                <button class="form__btn" type="submit" >
                    Сохранить
                </button>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    document.getElementById('firebase_token').value = localStorage['user_token']
</script>
{% endblock %}

templates/pages/registration-number.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}


{% block content %}
    <div id="changeble_div">
        <div class="box__wrap">
            <div class="form__box">
                <form method="get" action="{% url 'phone-verify' %}" data-url id="registration-form">
                    {% csrf_token %}
                    <div class="form__box-head">
                        <h2 class="form__title">
                            Для продолжения, введите номер телефона
                        </h2>
                    </div>

                    <label class="form__input-wrap">
                        <input type="text" id="phone_number" name="phone_number" class="form__input form__input-tel" required>
                    </label>

                    <div id="error-message">
                    </div>
                    <button class="form__btn" type="submit">
                        Отправить код
                    </button>
                </form>
            </div>
        </div>
    </div>

    <button id='sign-in-button'  hidden></button>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/phone_number_verify.js' %}"></script>
{% endblock %}

templates/pages/registration.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}

{% block content %}

    <div class="box__wrap">
        <div class="form__box">

            <form action="{% url 'verifier' %}" method="post">
                {% csrf_token %}
                <div class="form__box-head">
                    <h2 class="form__title">
                        Регистрация
                    </h2>
                </div>
                <input id="firebase_token_id" name="firebase_token_id" type="hidden">
                <label class="form__input-wrap">
                    <input type="text" id="id_first_name" name="first_name" class="form__input" placeholder="Имя" required>
                </label>
                <label class="form__input-wrap">
                    <input type="text" id="id_last_name" name="last_name" class="form__input" placeholder="Фамилия" required>
                </label>
                <label class="form__input-wrap form__password-input-wrap">
                    <input type="password" id="id_password1" name="password1" class="form__input" placeholder="Придумайте пароль" required>
                    <div class="form__eye"></div>
                </label>
                <label class="form__input-wrap form__password-input-wrap">
                    <input type="password" id="id_password2" name="password2" class="form__input" placeholder="Повторите пароль" required>
                    <div class="form__eye"></div>
                </label>
                <div style="text-align: center">{{ form.errors }}</div>
                {{ form.error }}
                {{ form.phone_number }}
                <button class="form__btn" type="submit">
                    Зарегистрироваться
                </button>
            </form>
        </div>
    </div>

    <div class="success__notification">
        Регистрация прошла успешно
    </div>


{% endblock %}

{% block scripts %}
<script>
        document.getElementById('phone_number').value = localStorage['user_token']
</script>

{% endblock %}

templates/pages/sign-in.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}

{% block style-libs %}{% endblock %}

{% block style %}{% endblock %}

{% block content %}

    <div class="box__wrap">
        <div class="form__box">
            <form method="post" id="sign-in-form">
                   {% csrf_token %}
                <div class="form__box-head">
                    <h2 class="form__title">
                        Авторизация
                    </h2>
                    <a href="{% url 'phone-verifier' %}" class="form__reg">
                        Регистрация
                    </a>
                </div>
                <label class="form__input-wrap">
                    <input type="text" class="form__input form__input-tel" id="id_username" required name="username">
                </label>

                <label class="form__input-wrap form__password-input-wrap">
                    <input type="password" class="form__input" placeholder="Введите пароль" id="id_password" name="password" required >
                    <div class="form__eye"></div>
                </label>
                {{ form.non_field_errors }}
                <button id="valid_number" onclick="getNumber()" class="form__btn" name="login" type="submit">
                    Войти
                </button>
                <a href="{% url 'password-reset-number' %}" class="forget__password">
                    Забыли пароль?
                </a>
            </form>
        </div>
    </div>

{% endblock %}

{% block scripts %}
<script>

function getNumber() {
    let countryCode = document.getElementsByClassName("iti__selected-dial-code")[0].innerText;
    let inputNumber = document.getElementsByClassName("form__input form__input-tel").item(0).value;
    let phoneNumber = countryCode + inputNumber
    document.getElementsByClassName('form__input form__input-tel').item(0).value = phoneNumber.replace(/\s+/g, "")
    document.getElementsByClassName(".form__btn")
    console.log(phoneNumber)

}
</script>

{% endblock %}